name = "sm-bill-tracker"
main = "src/index.ts"
compatibility_date = "2024-12-01"

assets = { directory = "public" }

[[d1_databases]]
binding = "DB"
database_name = "sm-bill-tracker"
database_id = "local"

[[kv_namespaces]]
binding = "SESSIONS"
id = "local"

[triggers]
crons = ["0 6 * * *"]
